[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "/setup-models.sh"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "always"

[env]
OLLAMA_HOST = "0.0.0.0"
OLLAMA_ORIGINS = "*"
